service: quiche-holder-engine

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions

functions:
    getImage:
        handler: index.php
        description: 'Returns a base64 encoded image of a Quiche, scaled and cropped to provided width and height.'
        layers:
            - ${bref:layer.php-74}
            - ${bref:extra.imagick-php-74}

# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
